config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :players
  resources :newsletters
  resources :games
  devise_for :users
  root 'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :name, :access_token, presence: true
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  has_many :recipients

  after_commit :set_job

  def ransack_query
    res_hash = {}
    filters.each do |filter|
      res_hash["#{filter['prop_name']}_#{filter['logic']}".parameterize.underscore.to_sym] = filter['value']
    end
    res_hash
  end

  private

  def set_job
    StartNewsletterWorker.perform_at(start_at, id)
  end

end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, :vk_id, presence: true

  def self.prop_names
    column_names - ['id', 'created_at', 'updated_at']
  end

end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :player
  belongs_to :newsletter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :access_token)
    end
end

app/controllers/newsletters_controller.rb
require_relative '../forms/newsletter_form'
require_relative '../workers/start_newsletter_worker'
class NewslettersController < ApplicationController

  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter_form = NewsletterForm.new(Newsletter.new())
    @newsletter_form.filters = []
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter_form = NewsletterForm.new(Newsletter.new(newsletter_params))

    respond_to do |format|
      if @newsletter_form.validate(newsletter_params)
        @newsletter_form.save
        format.html { redirect_to newsletters_path, notice: 'Newsletter was successfully created.' }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    @newsletter_form = NewsletterForm.new(@newsletter)

    respond_to do |format|
      if @newsletter_form.validate(newsletter_params)
        @newsletter_form.save
        format.html { redirect_to newsletters_path, notice: 'Newsletter was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit }
        format.json { render json: @newsletter_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: 'Newsletter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
      @newsletter_form = NewsletterForm.new(@newsletter)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(
        :name,
        :text,
        :start_at,
        filters: [
          :prop_name,
          :logic,
          :value
        ]
      )
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :vk_id, :level, :last_visit, :paid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/dashboard/index.html.slim
h1 Dashboard#index
p Find me in app/views/dashboard/index.html.slim

app/views/game_users/_form.html.slim
= form_for @game_user do |f|
  - if @game_user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game_user.errors.count, "error")} prohibited this game_user from being saved:"
      ul
        - @game_user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :vk_id
    = f.text_field :vk_id
  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :last_visit
    = f.datetime_select :last_visit
  .field
    = f.label :paid
    = f.check_box :paid
  .actions = f.submit

app/views/games/_form.html.slim
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      ul
        - @game.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :access_token
    = f.text_field :access_token
  .actions = f.submit

app/views/games/edit.html.slim
h1 Editing game

== render 'form'

= link_to 'Show', @game
'|
= link_to 'Back', games_path

app/views/games/index.html.slim
h1 Games

table
  thead
    tr
      th Name
      th Access token
      th
      th
      th

  tbody
    - @games.each do |game|
      tr
        td = game.name
        td = game.access_token
        td = link_to 'Show', game
        td = link_to 'Edit', edit_game_path(game)
        td = link_to 'Destroy', game, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Game', new_game_path

app/views/games/new.html.slim
h1 New game

== render 'form'

= link_to 'Back', games_path

app/views/games/show.html.slim
p#notice = notice

p
  strong Name:
  = @game.name
p
  strong Access token:
  = @game.access_token

= link_to 'Edit', edit_game_path(@game)
'|
= link_to 'Back', games_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title SqSender
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container-fluid.admin-panel
      #sidebar-wrapper
        .sidebar-nav
          ul.list-unstyled
            li =link_to 'Games', games_path
            li =link_to 'Players', players_path
            li =link_to 'Newsletters', newsletters_path
      #page-content-wrapper
        .p-20
          -if notice.present?
            .notice.alert.alert-info = notice
          -if alert.present?
            .alert.alert-danger = alert
          = yield

app/views/layouts/welcome.html.slim
doctype html
html
  head
    title SqSender
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container-fluid
      .sidebar
        =render 'components/menu'
      .content
        p.notice = notice
        p.alert = alert
        = yield

app/views/newsletters/_form.html.slim
= form_for @newsletter_form do |f|
  - if @newsletter_form.errors.any?
    #error_explanation
      h2 = "#{pluralize(@newsletter_form.errors.count, "error")} prohibited this newsletter from being saved:"
      ul
        - @newsletter_form.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .field
    =f.label :filters
    table
      tbody#filters_container
        tr
          th Свойство
          th Правило
          th Значение
          th

          -@newsletter_form.filters.each do |filter, key|
            tr
              td = select_tag "newsletter[filters][#{key}][prop_name]", options_for_select(Player.prop_names, filter['prop_name'])
              td = select_tag "newsletter[filters][#{key}][logic]", options_for_select([:eq, :gteq, :lteq], filter['logic'])
              td = text_field_tag "newsletter[filters][#{key}][value]", filter['value']
              td =link_to 'remove', '#', data: {remove_news_letter_filter_item: ''}
      tfoot
        tr
          td colspan=3
            =link_to 'add', '#', data: {add_news_letter_filter: ''}
          /tr
            td = select_tag 'newsletter[filters][][prop_name]', options_for_select([''] + Player.prop_names)
            td = select_tag 'newsletter[filters][][logic]', options_for_select(['', :eq, :gteq, :lteq])
            td = text_field_tag 'newsletter[filters][][value]'
  .field
    = f.label :text
    = f.text_area :text, class: 'form-control'
  .field
    = f.label :start_at
    .form-inline
      = f.datetime_select :start_at
  .actions = f.submit

app/views/newsletters/edit.html.slim
h1 Editing newsletter

== render 'form'

= link_to 'Show', @newsletter
'|
= link_to 'Back', newsletters_path

app/views/newsletters/index.html.slim
h1 Newsletters

table
  thead
    tr
      th Name
      th Filters
      th Start at
      th
      th
      th

  tbody
    - @newsletters.each do |newsletter|
      tr
        td = newsletter.name
        td
          -newsletter.filters.each do |filter|
            div
              = filter['prop_name'] + ' | '
              = filter['logic'] + ' | '
              = filter['value']
        td = newsletter.start_at
        td = link_to 'Show', newsletter
        td = link_to 'Edit', edit_newsletter_path(newsletter)
        td = link_to 'Destroy', newsletter, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Newsletter', new_newsletter_path

app/views/newsletters/new.html.slim
h1 New newsletter

== render 'form'

= link_to 'Back', newsletters_path

app/views/newsletters/show.html.slim
p#notice = notice

div
  strong Name:
  div
  = @newsletter.name
div.mt-10
  strong Text:
  div
  = @newsletter.text
div.mt-10
  strong Start at:
  div
  = @newsletter.start_at
div.mt-10
  strong Filters:
  - @newsletter.filters.each do |filter|
    div
      = filter['prop_name'] + ' | '
      = filter['logic'] + ' | '
      = filter['value']
div.mt-10
  strong Progress
  div#stat
    div = "Success:   #{@newsletter.recipients.where(sent: true).count}"
    div = "Errors:    #{@newsletter.recipients.where(error: true).count}"
    div = "Total:     #{@newsletter.recipients.count}"


= link_to 'Edit', edit_newsletter_path(@newsletter)
'|
= link_to 'Back', newsletters_path

app/views/players/_form.html.slim
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      h2 = "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      ul
        - @player.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :vk_id
    = f.text_field :vk_id
  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :last_visit
    = f.datetime_select :last_visit
  .field
    = f.label :paid
    = f.check_box :paid
  .actions = f.submit

app/views/players/edit.html.slim
h1 Editing player

== render 'form'

= link_to 'Show', @player
'|
= link_to 'Back', players_path

app/views/players/index.html.slim
h1 Players

table
  thead
    tr
      th Name
      th Vk
      th Level
      th Last visit
      th Paid
      th
      th
      th

  tbody
    - @players.each do |player|
      tr
        td = player.name
        td = player.vk_id
        td = player.level
        td = player.last_visit
        td = player.paid
        td = link_to 'Show', player
        td = link_to 'Edit', edit_player_path(player)
        td = link_to 'Destroy', player, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Player', new_player_path

app/views/players/new.html.slim
h1 New player

== render 'form'

= link_to 'Back', players_path

app/views/players/show.html.slim
p#notice = notice

p
  strong Name:
  = @player.name
p
  strong Vk:
  = @player.vk_id
p
  strong Level:
  = @player.level
p
  strong Last visit:
  = @player.last_visit
p
  strong Paid:
  = @player.paid

= link_to 'Edit', edit_player_path(@player)
'|
= link_to 'Back', players_path